services:
  # Backend API Service
  - type: web
    name: dilan-ai-backend
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: dilan-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DEBUG
        value: False
      - key: APP_NAME
        value: Dilan AI Backend
    healthCheckPath: /

databases:
  # PostgreSQL Database
  - name: dilan-db
    databaseName: dilan_db
    user: dilan_user
    plan: free
